id: IC5704926
ocr_import_info:
  timestamp: '2023-06-28T22:36:48.481570+00:00'
  batch_id: batch-5a8f
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-29 00:40:07.357489+00:00
last_modified: 2023-06-29 00:40:07.357495+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN26207
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN26207
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱང་ཆུབ་ལམ་སྒྲོན་གྱི་དཀའ་འགྲེལ།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9575386935556373
  ocr_word_median_confidence_index: 0.99956745
bases:
  I3CN26216:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN26216
      total_pages: 1106
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN26216.txt
    statistics:
      ocr_word_median_confidence_index: 0.99956745
      ocr_word_mean_confidence_index: 0.9575386935556373
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
